config/routes.rb
Rails.application.routes.draw do

  get 'requests/index'
  # ----------------------- Root ----------------------- #
  root to: 'session#new'
  get "/login" => "session#new"

  # ----------------------- Session ----------------------- #
  get "/login" => "session#new" # Login form
  post "/login" => "session#create" # Form submits here, do authentication & create session, redirect or show form with errors
  delete "/login" => "session#destroy" # Logout, delete session

  # ----------------------- Users ----------------------- #
  get "/users/search/:query" => "users#user_search"
  get "/users/profile/:query" => "users#user_profile"

  resources :users do
    # ----------------------- Friends ----------------------- #
    resources :friends
    # ----------------------- Requests ----------------------- #
    resources :requests
  end

  get "/requests" => "requests#index"
  
  # ----------------------- Messages ----------------------- #
  get "/messages/search" => "messages#message_search"
  get "/messages/show/:query" => "messages#message_show"

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  post "/messages" => "messages#create"
  resources :messages

end

app/models/user.rb
class User < ApplicationRecord

  # ------------------------ Friends ----------------------- #
  # Define friend requests sent & received
  has_many :request_sent, class_name: "Friendship", foreign_key: "user_id", inverse_of: "user", dependent: :destroy
  has_many :request_received, class_name: "Friendship", foreign_key: "friend_id", inverse_of: "friend", dependent: :destroy

  # Get friends list
  has_many :friends_sent_confirmed, -> {merge(Friendship.friends)}, through: :request_sent, source: :friend
  has_many :friends_request_confirmed, -> {merge(Friendship.friends)}, through: :request_received, source: :user

  def friends
    (friends_sent_confirmed + friends_request_confirmed).uniq.sort_by(&:created_at)
  end

  # Unconfirmed friend requests
  has_many :pending_requests, -> {merge(Friendship.pending_friends)}, through: :request_sent, source: :friend
  has_many :received_requests, -> {merge(Friendship.pending_friends)}, through: :request_received, source: :user

  # ------------------------ Message ----------------------- #
  # Get messages
  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id", inverse_of: "sender", dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id", inverse_of: "recipient", dependent: :destroy

  def all_messages
    (sent_messages + received_messages).sort_by(&:created_at)
  end

  # Get messaged friends
  has_many :sent_messages_friends, -> {merge(User.all)}, through: :sent_messages, source: :recipient
  has_many :received_messages_friends, -> {merge(User.all)}, through: :received_messages, source: :sender

  def all_messaged_friends
    (sent_messages_friends + received_messages_friends).uniq.sort_by(&:created_at)
  end

  # ---------------------- Validations ---------------------- #
  has_secure_password
  validates :name, presence: true, length: { minimum: 2, maximum: 30 }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, maximum: 16}, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  before_action :check_if_logged_in, except: [:new, :create]

  def new
    @user = User.new
  end #new

  def create
    @user = User.create user_params
    if @user.persisted?
      session[:user_id] = @user.id #log in the newly created account automatically!
      redirect_to user_friends_path(@user.id)
    else
      render :new
    end #else
  end #create

  def index
    # @user = User.all
  end

  def show
    @user = User.find params[:id]
    # redirect_to(user_path(params[:id])) unless @user.id == @current_user.id
    @friend = Friendship.new

  end

  def edit
    @user = User.find params[:id] #from /users/:id
    redirect_to(user_path(params[:id])) unless @user.id == @current_user.id
  end

  def update
    @user = User.find params[:id] #from /users/:id
    if @user.id != @current_user.id
      redirect_to(user_path(params[:id]))
      return
    end
    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      @user.image = response['public_id']
      @user.save
      # raise "hell"
      @user.update user_params
    end
    redirect_to user_path(@user)
  end

  def destroy
  end

  def user_search
    render json: User.where("name ILIKE ?", "%#{params[:query]}%")
  end

  def user_profile
    @user = User.find(params[:query])
    render layout: false
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end # user_params

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="container user_profile">
<h1>Edit Profile</h1>
<hr>
<div class="form edit_form">
  <%= form_for @user, html: {multipart: true} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :image, "Edit Profile Image:" %>
    <%= f.cl_image_upload :image %>
    <br>
    <%= f.submit nil, class: "edit_button", style: "background-color: #262525" %>
  <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<div class="container user_profile">
<h1>Create an Account</h1>
<hr>
​
<% if @user.errors.full_messages.any? %>
  <ul>
    <% @user.errors.full_messages.each do |e| %>
    <li><%= e %></li>
    <% end %>
  </ul>
<% end %>
<div class="form edit_form">
<%= form_for @user do |f| %>
​
  <%= f.label :name %>
  <%= f.text_field :name %>
​
  <%= f.label :email %>
  <%= f.email_field :email %>
​
  <%= f.label :password %>
  <%= f.password_field :password %>
​
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br>
​
  <%= f.submit 'Sign Up', class: "edit_button", style: "background-color: #262525"%>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div class="container user_profile">
  <h1>Your Profile</h1>
  <hr>
  <h5>Name:</h5>
  <h3><%= @user.name %></h3>
  <br>
  <h5>Email: </h5>
  <h3><%= @user.email %></h3>
  <br>
  <h5>Profile Image: </h5>
  <div class="user_avatar">
    <%= check_user_image_large(@user) %>
  </div>

  <% if @user.id === @current_user.id %>
    <p><%= link_to "Edit profile", edit_user_path %></p>
  <% elsif @current_user.friends.include? @user %>
    <%= button_to "Message", messages_path(@user.id), class: "message_friends", id: @user.id, method: :get %>
    <%= link_to "Unfriend", user_friend_path(@user.id, @current_user.id), method: "delete" %>
  <% elsif @current_user.pending_requests.include? @user %>
    <p>Waiting for Approval</p>
  <% elsif @current_user.received_requests.include? @user %>
    <%= button_to "Accept Friend", messages_path(@user.id), id: "accept_friend", friend_id: @user.id, current_user_id: @current_user.id, method: :get %>
  <% else %>
    <div>
      <button id="add_friend" friend_id="<%= @user.id %>">Add Friend</button>
      <div class="hide">
      <%= button_to "Cancel Request", user_friend_path(@user.id, @current_user.id), method: "delete" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/user_profile.html.erb
<div class="container user_profile">
  <h5>Name:</h5>
  <h3><%= @user.name %></h3>
  <br>
  <h5>Email: </h5>
  <h3><%= @user.email %></h3>
  <br>
  <h5>Profile Image: </h5>
  <div class="user_avatar">
    <%= check_user_image_large(@user) %>
  </div>

  <% if @user.id === @current_user.id %>
    <p><%= link_to "Edit profile", edit_user_path %></p>
  <% elsif @current_user.friends.include? @user %>
    <%= button_to "Message", messages_path(@user.id), class: "message_friends", id: @user.id, method: :get %>
    <%= link_to "Unfriend", user_friend_path(@user.id, @current_user.id), method: "delete" %>
  <% elsif @current_user.pending_requests.include? @user %>
    <p>Waiting for Approval</p>
  <% elsif @current_user.received_requests.include? @user %>
    <button id="accept_friend" friend_id="<%= @user.id %>" current_user_id="<%= @current_user.id %>">Accept Friend</button>
  <% else %>
    <%# button_to "Add Friend", user_friends_path(@user.id), method: :post %>
    <button id="add_friend" friend_id="<%= @user.id %>">Add Friend</button>
  <% end %>
</div>