config/routes.rb
Rails.application.routes.draw do

  get 'requests/index'
  # ----------------------- Root ----------------------- #
  root to: 'session#new'
  get "/login" => "session#new"

  # ----------------------- Session ----------------------- #
  get "/login" => "session#new" # Login form
  post "/login" => "session#create" # Form submits here, do authentication & create session, redirect or show form with errors
  delete "/login" => "session#destroy" # Logout, delete session

  # ----------------------- Users ----------------------- #
  get "/users/search/:query" => "users#user_search"
  get "/users/profile/:query" => "users#user_profile"

  resources :users do
    # ----------------------- Friends ----------------------- #
    resources :friends
    # ----------------------- Requests ----------------------- #
    resources :requests
  end

  get "/requests" => "requests#index"
  
  # ----------------------- Messages ----------------------- #
  get "/messages/search" => "messages#message_search"
  get "/messages/show/:query" => "messages#message_show"

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  post "/messages" => "messages#create"
  resources :messages

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GA-Chat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <%= cloudinary_js_config %>

  </head>

  <body class="container-fluid no-padding">
    <div class="notification hide">
    </div>
    <div class="row no-gutters">
    <nav class="col-2 main_nav">
      <div class="main_nav_logo_wrapper">
        <%= link_to image_tag("ga_logo.svg", alt: "Ga-Chat Logo", class: "logo"), messages_path %>
      </div>
      <div class="main_nav_item_wrapper">
        <ul class="main_nav_item">
          <% if @current_user.present? %>
          <li><%= link_to @current_user.name, user_path(@current_user) %></li>
          <li><%= link_to "Messages", messages_path %></li>
          <li><%= link_to "Friends", user_friends_path(@current_user) %></li>
          <li><%= link_to "Requests", user_requests_path(@current_user) %></li>
          <li><%= link_to 'Logout', login_path, method: 'delete' %></li>
          <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Create Account', new_user_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="copy_msg">
        <p>&copy; SEI37 Productions</p>
      </div>
    </nav>

    <div class="col-9">
      <div class="container-fluid no-padding">
        <%= yield %>
      </div>
    </div>


    </div>

  </body>

</html>